const M=DailyCutModel,$=id=>document.getElementById(id),today=M.localDate(new Date());
let state=M.migrate(localStorage),editingProductId=null;
const fields=['steps','distance','burn','foodOverride','proteinOverride','sodiumOverride','notes'];
function n(id){return M.number($(id).value)}function opt(id){return M.optional($(id).value)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function currentReport(){return state.reports[state.selectedDate]||{};}function persist(){M.save(localStorage,state);render();}
function loadReportForm(){const r=currentReport();$('steps').value=r.steps??'';$('distance').value=r.distance??'';$('burn').value=r.burn??'';$('foodOverride').value=r.foodOverride??'';$('proteinOverride').value=r.proteinOverride??'';$('sodiumOverride').value=r.sodiumOverride??'';$('notes').value=r.notes??'';}
function saveReport(){state.reports[state.selectedDate]={steps:n('steps'),distance:n('distance'),burn:opt('burn'),foodOverride:opt('foodOverride'),proteinOverride:opt('proteinOverride'),sodiumOverride:opt('sodiumOverride'),notes:$('notes').value.trim()};persist();}
function metric(label,value){return `<div class="metric"><span>${label}</span><strong>${value}</strong></div>`;}
function money(micros){return `${state.settings.currencyCode} ${(M.number(micros)/1e6).toFixed(2)}`;}
function render(){
  $('selectedDate').value=state.selectedDate;$('selectedDate').max=today;$('nextDate').disabled=state.selectedDate>=today;
  const r=M.report(state,state.selectedDate),t=r.food,sign=r.deficit>=0?'−':'+',spend=M.spending(state,state.selectedDate),allowance=M.effectiveCalories(state.settings);
  $('resultCard').innerHTML=`<h2>${esc(r.verdict)}</h2><div class="deficit">${r.burn>0?sign+Math.abs(Math.round(r.deficit)).toLocaleString()+' kcal':'Unavailable'}</div>${metric('Burn',Math.round(r.burn)+' kcal')}${metric('Food',Math.round(r.calories)+' kcal')}${metric('Allowance',Math.round(allowance)+' kcal')}`;
  $('nutritionCard').innerHTML=`<h2>Daily nutrition and spending</h2>${metric('Entries',t.entries)}${metric('Calories',Math.round(t.calories)+' kcal')}${metric('Protein',Math.round(t.protein)+' g')}${metric('Sodium',Math.round(t.sodium)+' mg')}${metric('Known spending',money(spend.knownTotalMicros))}${metric('Budget',money(state.settings.dailyBudgetMicros))}${spend.unknownEntries?`<p class="muted">${spend.unknownEntries} cost(s) unknown.</p>`:''}`;
  const query=$('productSearch').value.toLowerCase();$('productList').innerHTML=Object.values(state.products).filter(p=>[p.name,p.brand,p.barcode].join(' ').toLowerCase().includes(query)).map(p=>`<div class="list-row"><div class="details"><strong>${esc(p.name)}</strong><br><small>${esc([p.brand,p.barcode].filter(Boolean).join(' · '))}${p.purchasePriceMicros==null?'':' · '+money(p.purchasePriceMicros)+' / '+p.purchaseUnitServings+' serving(s)'} · ${p.includeInPlanner===false?'not planned':(p.plannerItemType||'FOOD').toLowerCase()+(p.alwaysIncludeInPlanner?' · fixed':'')}</small></div><div class="row-actions"><button data-edit-product="${esc(p.productId)}">Edit</button><button data-add-product="${esc(p.productId)}">Add</button></div></div>`).join('')||'<p class="muted">No saved products.</p>';
  $('foodLog').innerHTML=state.logs.filter(x=>x.date===state.selectedDate).sort((a,b)=>b.id-a.id).map(x=>{const cost=x.actualPaidTotalMicros??(x.catalogCostPerServingMicros==null?null:Math.round(x.catalogCostPerServingMicros*x.quantity));return `<div class="list-row"><div class="details"><strong>${x.quantity} × ${esc(x.name)}</strong><br><small>${Math.round(x.calories*x.quantity)} kcal · ${Math.round(x.protein*x.quantity)} g protein · ${cost==null?'cost unknown':money(cost)}${x.excludeCostFromBudget?' · ignored in budget':''}</small></div><div class="row-actions"><button data-edit-log="${x.id}">Edit</button><button data-delete-log="${x.id}" class="danger">Delete</button></div></div>`;}).join('')||'<p class="muted">No food entries for this date.</p>';
}
function productFromForm(){return{productId:editingProductId||M.uuid(),barcode:$('productBarcode').value.trim()||null,name:$('productName').value.trim(),brand:$('productBrand').value.trim(),servingLabel:$('productServing').value.trim()||'1 serving',calories:n('productCalories'),protein:n('productProtein'),sodium:n('productSodium'),carbs:n('productCarbs'),fat:n('productFat'),sugar:n('productSugar'),fiber:n('productFiber'),saturated:n('productSaturated'),purchasePriceMicros:$('productPrice').value.trim()===''?null:Math.round(n('productPrice')*1e6),purchaseUnitServings:n('productPurchaseServings')||1,includeInPlanner:$('productIncludePlanner').checked,plannerItemType:$('productPlannerType').value,alwaysIncludeInPlanner:$('productFixedPlanner').checked};}
function fillProduct(p={}){editingProductId=p.productId||null;for(const [id,key] of Object.entries({productBarcode:'barcode',productName:'name',productBrand:'brand',productServing:'servingLabel',productCalories:'calories',productProtein:'protein',productSodium:'sodium',productCarbs:'carbs',productFat:'fat',productSugar:'sugar',productFiber:'fiber',productSaturated:'saturated',productPurchaseServings:'purchaseUnitServings'}))$(id).value=p[key]??(key==='servingLabel'?'1 serving':key==='purchaseUnitServings'?1:'');$('productPrice').value=p.purchasePriceMicros==null?'':p.purchasePriceMicros/1e6;$('productIncludePlanner').checked=p.includeInPlanner??true;$('productPlannerType').value=p.plannerItemType||'FOOD';$('productFixedPlanner').checked=p.alwaysIncludeInPlanner??false;$('productFormTitle').scrollIntoView({behavior:'smooth'});}
function paidPrompt(product,quantity){const estimate=product.purchasePriceMicros==null?'':String((product.purchasePriceMicros/(product.purchaseUnitServings||1)*quantity)/1e6);const value=prompt('Actual paid total (blank uses catalog estimate, 0 means free)',estimate);return value===null?undefined:value.trim()===''?null:Math.round(Number(value)*1e6);}
function ignorePricePrompt(){return confirm('Ignore this entry price in daily budget calculations?');}
function saveProduct(add){const p=productFromForm();if(!p.name)return alert('Product name is required.');try{M.upsertProduct(state,p);editingProductId=p.productId;if(add){const q=n('productQuantity')||1,paid=paidPrompt(p,q);if(paid!==undefined)M.addLog(state,state.selectedDate,p,q,paid,ignorePricePrompt());}persist();}catch(error){alert(error.message);}}
function useBarcode(){const code=$('barcodeLookup').value.trim();if(!code)return;const p=M.findBarcode(state,code);if(!p){fillProduct({barcode:code});return alert('Unknown barcode. Complete the product editor.');}const q=Number(prompt(`Quantity for ${p.name}`,'1'));if(q>0){const paid=paidPrompt(p,q);if(paid!==undefined){M.addLog(state,state.selectedDate,p,q,paid,ignorePricePrompt());persist();}}}
document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.add('hidden'));$(button.dataset.tab+'Tab').classList.remove('hidden');}));
$('previousDate').onclick=()=>{const d=new Date(state.selectedDate+'T12:00:00');d.setDate(d.getDate()-1);state.selectedDate=M.localDate(d);loadReportForm();persist();};
$('nextDate').onclick=()=>{const d=new Date(state.selectedDate+'T12:00:00');d.setDate(d.getDate()+1);state.selectedDate=M.localDate(d)>today?today:M.localDate(d);loadReportForm();persist();};
$('selectedDate').onchange=e=>{state.selectedDate=e.target.value>today?today:e.target.value;loadReportForm();persist();};$('saveReport').onclick=saveReport;$('useBarcode').onclick=useBarcode;$('saveProduct').onclick=()=>saveProduct(false);$('saveAndAddProduct').onclick=()=>saveProduct(true);$('productSearch').oninput=render;
$('productList').onclick=e=>{const edit=e.target.dataset.editProduct,add=e.target.dataset.addProduct;if(edit)fillProduct(state.products[edit]);if(add){const p=state.products[add],q=Number(prompt(`Quantity for ${p.name}`,'1'));if(q>0){const paid=paidPrompt(p,q);if(paid!==undefined){M.addLog(state,state.selectedDate,p,q,paid,ignorePricePrompt());persist();}}}};
$('foodLog').onclick=e=>{const edit=Number(e.target.dataset.editLog),del=Number(e.target.dataset.deleteLog);if(edit){const log=state.logs.find(x=>x.id===edit),q=Number(prompt('Quantity',log.quantity)),paidText=prompt('Actual paid total (blank uses catalog estimate, 0 means free)',log.actualPaidTotalMicros==null?'':log.actualPaidTotalMicros/1e6);if(q>0&&paidText!==null)M.updateLog(state,edit,{quantity:q,actualPaidTotalMicros:paidText.trim()===''?null:Math.round(Number(paidText)*1e6),excludeCostFromBudget:ignorePricePrompt()});persist();}if(del&&confirm('Delete this food entry?')){M.deleteLog(state,del);persist();}};
$('planDay').onclick=()=>{const result=M.plan(state,state.selectedDate);$('planResults').innerHTML=(result.message?`<p class="muted">${esc(result.message)}</p>`:'')+(result.spendingIncomplete?'<p class="muted">Existing costs are incomplete.</p>':'')+(result.excludedFromPlanningProducts?`<p class="muted">${result.excludedFromPlanningProducts} product(s) disabled for planning.</p>`:'')+result.plans.map((p,i)=>`<div class="list-row"><div class="details"><strong>Option ${i+1}</strong><br>${p.items.map(x=>`${x.purchaseUnits} × ${esc(x.name)}${x.fixed?' · fixed':''}`).join('<br>')}<br><small>${money(p.totalCostMicros)} additional · ${Math.round(p.nutrition.calories)} kcal · ${Math.round(p.nutrition.protein)} g protein</small></div></div>`).join('');};
function loadGoals(){const s=state.settings;for(const [id,key] of Object.entries({goalMode:'goalMode',goalCalories:'calories',goalBurn:'expectedBurnCalories',goalDeficit:'desiredDeficitCalories',goalProtein:'protein',goalSodium:'sodium',goalCarbs:'carbs',goalFat:'fat',goalSugar:'sugar',goalFiber:'fiber',goalSaturated:'saturated',currencyCode:'currencyCode'}))$(id).value=s[key];$('dailyBudget').value=(s.dailyBudgetMicros||0)/1e6;}
$('saveGoals').onclick=()=>{state.settings={goalMode:$('goalMode').value,calories:n('goalCalories'),expectedBurnCalories:n('goalBurn'),desiredDeficitCalories:n('goalDeficit'),protein:n('goalProtein'),sodium:n('goalSodium'),carbs:n('goalCarbs'),fat:n('goalFat'),sugar:n('goalSugar'),fiber:n('goalFiber'),saturated:n('goalSaturated'),currencyCode:$('currencyCode').value.trim().toUpperCase(),dailyBudgetMicros:Math.round(n('dailyBudget')*1e6)};if(state.settings.expectedBurnCalories<=state.settings.desiredDeficitCalories)return alert('Expected burn must exceed desired deficit.');persist();};
$('clearData').onclick=()=>{if(confirm('Delete all preview data?')){Object.keys(localStorage).filter(key=>key===M.KEY||key===M.OLD_KEY||key.startsWith('dcr_')).forEach(key=>localStorage.removeItem(key));location.reload();}};
$('exportPng').onclick=()=>{const r=M.report(state,state.selectedDate),c=$('reportCanvas'),ctx=c.getContext('2d');c.width=1080;c.height=1450;ctx.fillStyle='#f4f6f7';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.roundRect(55,55,970,1320,35);ctx.fill();ctx.fillStyle='#1d2a32';ctx.font='800 56px system-ui';ctx.fillText('Daily Cut Report',95,145);ctx.font='30px system-ui';ctx.fillStyle='#63727b';ctx.fillText(r.date+' · offline preview',95,195);const rows=[['Verdict',r.verdict],['Steps',Math.round(r.steps||0).toLocaleString()],['Final burn',Math.round(r.burn)+' kcal'],['Food',Math.round(r.calories)+' kcal'],['Protein',Math.round(r.protein)+' g'],['Sodium',Math.round(r.sodium)+' mg'],['Estimated deficit',Math.round(r.deficit)+' kcal']];rows.forEach((row,i)=>{const y=300+i*115;ctx.fillStyle='#52616a';ctx.font='32px system-ui';ctx.fillText(row[0],95,y);ctx.fillStyle='#1d2a32';ctx.font='700 38px system-ui';ctx.textAlign='right';ctx.fillText(row[1],985,y);ctx.textAlign='left';});ctx.fillStyle='#63727b';ctx.font='27px system-ui';ctx.fillText((r.notes||'No notes.').slice(0,70),95,1160);ctx.fillText('Generated locally. No network requests.',95,1300);const a=document.createElement('a');a.download=`DailyCutReport_${r.date}.png`;a.href=c.toDataURL('image/png');a.click();};

function backupPayload(){
  const products=Object.values(state.products).map(p=>({productId:p.productId,barcode:p.barcode??null,name:p.name,brand:p.brand||'',servingLabel:p.servingLabel||'1 serving',calories:M.number(p.calories),proteinG:M.number(p.protein),sodiumMg:M.number(p.sodium),carbsG:M.number(p.carbs),fatG:M.number(p.fat),sugarG:M.number(p.sugar),fiberG:M.number(p.fiber),saturatedFatG:M.number(p.saturated),purchasePriceMicros:p.purchasePriceMicros??null,purchaseUnitServings:M.number(p.purchaseUnitServings)||1,includeInPlanner:p.includeInPlanner??true,plannerItemType:p.plannerItemType||'FOOD',alwaysIncludeInPlanner:p.alwaysIncludeInPlanner??false,notes:p.notes||'',createdAt:p.createdAt||Date.now(),updatedAt:p.updatedAt||Date.now()}));
  const productExtras=products.flatMap(p=>(state.products[p.productId].extras||[]).map(x=>({productId:p.productId,name:x.name,value:M.number(x.value),unit:x.unit||''})));
  const dailyReports=Object.entries(state.reports).map(([date,r])=>({date,steps:M.number(r.steps),distanceKm:M.number(r.distance),activeCalories:0,totalCalories:0,exerciseSessions:0,exerciseMinutes:0,nutritionCalories:0,nutritionProteinG:0,nutritionSodiumMg:0,nutritionRecords:0,healthConnectStatus:'Browser preview',manualFoodCalories:r.foodOverride??null,manualProteinG:r.proteinOverride??null,manualSodiumMg:r.sodiumOverride??null,manualBurnCalories:r.burn??null,notes:r.notes||'',savedAtEpochMs:Date.now()}));
  const foodLogs=state.logs.map(x=>({id:x.id,date:x.date,productId:x.productId??null,barcode:x.barcode??null,productName:x.name,brand:x.brand||'',servingLabel:x.servingLabel||'1 serving',quantity:M.number(x.quantity)||1,caloriesPerServing:M.number(x.calories),proteinGPerServing:M.number(x.protein),sodiumMgPerServing:M.number(x.sodium),carbsGPerServing:M.number(x.carbs),fatGPerServing:M.number(x.fat),sugarGPerServing:M.number(x.sugar),fiberGPerServing:M.number(x.fiber),saturatedFatGPerServing:M.number(x.saturated),catalogCostPerServingMicros:x.catalogCostPerServingMicros??null,actualPaidTotalMicros:x.actualPaidTotalMicros??null,excludeCostFromBudget:x.excludeCostFromBudget??false,loggedAt:x.loggedAt||Date.now()}));
  const dailyExtras=state.logs.flatMap(x=>(x.extras||[]).map((e,i)=>({id:Number(`${x.id}${i+1}`),logId:x.id,name:e.name,valuePerServing:M.number(e.value),unit:e.unit||''})));
  const s=state.settings;return{schemaVersion:2,createdAt:Date.now(),settings:{mode:s.goalMode,calories:s.calories,expectedBurnCalories:s.expectedBurnCalories,desiredDeficitCalories:s.desiredDeficitCalories,proteinG:s.protein,sodiumMg:s.sodium,carbsG:s.carbs,fatG:s.fat,sugarG:s.sugar,fiberG:s.fiber,saturatedFatG:s.saturated,currencyCode:s.currencyCode,dailyBudgetMicros:s.dailyBudgetMicros},products,productExtras,dailyReports,foodLogs,dailyExtras};
}
function restorePayload(p){if(![1,2].includes(p.schemaVersion))throw new Error('Unsupported backup schema.');const next=M.empty(today),extrasByProduct=Object.groupBy?Object.groupBy(p.productExtras||[],x=>x.productId):(p.productExtras||[]).reduce((a,x)=>((a[x.productId]??=[]).push(x),a),{});if(p.schemaVersion===2){const s=p.settings;next.settings={goalMode:s.mode,calories:s.calories,expectedBurnCalories:s.expectedBurnCalories,desiredDeficitCalories:s.desiredDeficitCalories,protein:s.proteinG,sodium:s.sodiumMg,carbs:s.carbsG,fat:s.fatG,sugar:s.sugarG,fiber:s.fiberG,saturated:s.saturatedFatG,currencyCode:s.currencyCode,dailyBudgetMicros:s.dailyBudgetMicros};}for(const product of p.products||[]){next.products[product.productId]={productId:product.productId,barcode:product.barcode,name:product.name,brand:product.brand,servingLabel:product.servingLabel,calories:product.calories,protein:product.proteinG,sodium:product.sodiumMg,carbs:product.carbsG,fat:product.fatG,sugar:product.sugarG,fiber:product.fiberG,saturated:product.saturatedFatG,purchasePriceMicros:product.purchasePriceMicros??null,purchaseUnitServings:product.purchaseUnitServings||1,includeInPlanner:product.includeInPlanner??true,plannerItemType:product.plannerItemType||'FOOD',alwaysIncludeInPlanner:product.alwaysIncludeInPlanner??false,notes:product.notes,createdAt:product.createdAt,updatedAt:product.updatedAt,extras:extrasByProduct[product.productId]||[]};}for(const r of p.dailyReports||[])next.reports[r.date]={steps:r.steps,distance:r.distanceKm,burn:r.totalCalories??0,notes:''};const extrasByLog=(p.dailyExtras||[]).reduce((a,x)=>((a[x.logId]??=[]).push({name:x.name,value:x.valuePerServing,unit:x.unit}),a),{});next.logs=(p.foodLogs||[]).map(x=>({id:x.id,date:x.date,productId:x.productId,barcode:x.barcode,name:x.productName,brand:x.brand,servingLabel:x.servingLabel,quantity:x.quantity,calories:x.caloriesPerServing,protein:x.proteinGPerServing,sodium:x.sodiumMgPerServing,carbs:x.carbsGPerServing,fat:x.fatGPerServing,sugar:x.sugarGPerServing,fiber:x.fiberGPerServing,saturated:x.saturatedFatGPerServing,catalogCostPerServingMicros:x.catalogCostPerServingMicros??null,actualPaidTotalMicros:x.actualPaidTotalMicros??null,excludeCostFromBudget:x.excludeCostFromBudget??false,loggedAt:x.loggedAt,extras:extrasByLog[x.id]||[]}));next.nextLogId=Math.max(0,...next.logs.map(x=>x.id))+1;M.seed(next);return next;}
$('exportBackup').onclick=async()=>{const password=prompt('Backup password (at least 8 characters)');if(!password||password.length<8)return alert('Use at least 8 characters.');const confirmPassword=prompt('Confirm backup password');if(password!==confirmPassword)return alert('Passwords do not match.');try{const bytes=await DailyCutBackup.encrypt(backupPayload(),password),a=document.createElement('a');a.download=`DailyCutReport_${today}.dcrbackup`;a.href=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(error){alert(`Backup failed: ${error.message}`);}};
$('importBackup').onclick=()=>{if(confirm('Restoring replaces all current preview data after validation. Continue?'))$('backupFile').click();};
$('backupFile').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;const password=prompt('Backup password');if(!password)return;try{const payload=await DailyCutBackup.decrypt(new Uint8Array(await file.arrayBuffer()),password),next=restorePayload(payload);state=next;editingProductId=null;loadReportForm();persist();alert('Backup restored.');}catch(error){alert(`Restore failed: ${error.message}`);}};
loadReportForm();loadGoals();render();
