const M=DailyCutModel,state=M.migrate(localStorage),$=id=>document.getElementById(id),today=M.localDate(new Date());
const fields=['steps','distance','burn','foodOverride','proteinOverride','sodiumOverride','notes'];
function n(id){return M.number($(id).value)}function opt(id){return M.optional($(id).value)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function currentReport(){return state.reports[state.selectedDate]||{};}function persist(){M.save(localStorage,state);render();}
function loadReportForm(){const r=currentReport();$('steps').value=r.steps??'';$('distance').value=r.distance??'';$('burn').value=r.burn??'';$('foodOverride').value=r.foodOverride??'';$('proteinOverride').value=r.proteinOverride??'';$('sodiumOverride').value=r.sodiumOverride??'';$('notes').value=r.notes??'';}
function saveReport(){state.reports[state.selectedDate]={steps:n('steps'),distance:n('distance'),burn:opt('burn'),foodOverride:opt('foodOverride'),proteinOverride:opt('proteinOverride'),sodiumOverride:opt('sodiumOverride'),notes:$('notes').value.trim()};persist();}
function metric(label,value){return `<div class="metric"><span>${label}</span><strong>${value}</strong></div>`;}
function render(){
  $('selectedDate').value=state.selectedDate;$('selectedDate').max=today;$('nextDate').disabled=state.selectedDate>=today;
  const r=M.report(state,state.selectedDate),t=r.food,sign=r.deficit>=0?'−':'+';
  $('resultCard').innerHTML=`<h2>${esc(r.verdict)}</h2><div class="deficit">${sign}${Math.abs(Math.round(r.deficit)).toLocaleString()} kcal</div>${metric('Burn',Math.round(r.burn)+' kcal')}${metric('Food',Math.round(r.calories)+' kcal')}${metric('Protein',Math.round(r.protein)+' g')}${metric('Sodium',Math.round(r.sodium)+' mg')}`;
  $('nutritionCard').innerHTML=`<h2>Daily nutrition</h2>${metric('Entries',t.entries)}${metric('Calories',Math.round(t.calories)+' kcal')}${metric('Protein',Math.round(t.protein)+' g')}${metric('Sodium',Math.round(t.sodium)+' mg')}${metric('Carbs',Math.round(t.carbs)+' g')}${metric('Fat',Math.round(t.fat)+' g')}`;
  const query=$('productSearch').value.toLowerCase();$('productList').innerHTML=Object.values(state.products).filter(p=>[p.name,p.brand,p.barcode].join(' ').toLowerCase().includes(query)).map(p=>`<div class="list-row"><div class="details"><strong>${esc(p.name)}</strong><br><small>${esc(p.brand)} · ${esc(p.barcode)}</small></div><div class="row-actions"><button data-edit-product="${esc(p.barcode)}">Edit</button><button data-add-product="${esc(p.barcode)}">Add</button></div></div>`).join('')||'<p class="muted">No saved products.</p>';
  $('foodLog').innerHTML=state.logs.filter(x=>x.date===state.selectedDate).sort((a,b)=>b.id-a.id).map(x=>`<div class="list-row"><div class="details"><strong>${x.quantity} × ${esc(x.name)}</strong><br><small>${Math.round(x.calories*x.quantity)} kcal · ${Math.round(x.protein*x.quantity)} g protein</small></div><div class="row-actions"><button data-edit-log="${x.id}">Edit</button><button data-delete-log="${x.id}" class="danger">Delete</button></div></div>`).join('')||'<p class="muted">No food entries for this date.</p>';
}
function productFromForm(){return{barcode:$('productBarcode').value.trim(),name:$('productName').value.trim(),brand:$('productBrand').value.trim(),servingLabel:$('productServing').value.trim()||'1 serving',calories:n('productCalories'),protein:n('productProtein'),sodium:n('productSodium'),carbs:n('productCarbs'),fat:n('productFat'),sugar:n('productSugar'),fiber:n('productFiber'),saturated:n('productSaturated')};}
function fillProduct(p={}){for(const [id,key] of Object.entries({productBarcode:'barcode',productName:'name',productBrand:'brand',productServing:'servingLabel',productCalories:'calories',productProtein:'protein',productSodium:'sodium',productCarbs:'carbs',productFat:'fat',productSugar:'sugar',productFiber:'fiber',productSaturated:'saturated'}))$(id).value=p[key]??(key==='servingLabel'?'1 serving':'');$('productFormTitle').scrollIntoView({behavior:'smooth'});}
function saveProduct(add){const p=productFromForm();if(!p.barcode||!p.name)return alert('Barcode and name are required.');M.upsertProduct(state,p);if(add)M.addLog(state,state.selectedDate,p,n('productQuantity')||1);persist();}
function useBarcode(){const code=$('barcodeLookup').value.trim();if(!code)return;const p=state.products[code];if(!p){fillProduct({barcode:code});return alert('Unknown barcode. Complete the product editor.');}const q=Number(prompt(`Quantity for ${p.name}`, '1'));if(q>0){M.addLog(state,state.selectedDate,p,q);persist();}}
document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.add('hidden'));$(button.dataset.tab+'Tab').classList.remove('hidden');}));
$('previousDate').onclick=()=>{const d=new Date(state.selectedDate+'T12:00:00');d.setDate(d.getDate()-1);state.selectedDate=M.localDate(d);loadReportForm();persist();};
$('nextDate').onclick=()=>{const d=new Date(state.selectedDate+'T12:00:00');d.setDate(d.getDate()+1);state.selectedDate=M.localDate(d)>today?today:M.localDate(d);loadReportForm();persist();};
$('selectedDate').onchange=e=>{state.selectedDate=e.target.value>today?today:e.target.value;loadReportForm();persist();};$('saveReport').onclick=saveReport;$('useBarcode').onclick=useBarcode;$('saveProduct').onclick=()=>saveProduct(false);$('saveAndAddProduct').onclick=()=>saveProduct(true);$('productSearch').oninput=render;
$('productList').onclick=e=>{const edit=e.target.dataset.editProduct,add=e.target.dataset.addProduct;if(edit)fillProduct(state.products[edit]);if(add){const p=state.products[add],q=Number(prompt(`Quantity for ${p.name}`,'1'));if(q>0){M.addLog(state,state.selectedDate,p,q);persist();}}};
$('foodLog').onclick=e=>{const edit=Number(e.target.dataset.editLog),del=Number(e.target.dataset.deleteLog);if(edit){const log=state.logs.find(x=>x.id===edit),q=Number(prompt('Quantity',log.quantity)),cal=Number(prompt('Calories per serving',log.calories)),protein=Number(prompt('Protein g per serving',log.protein)),sodium=Number(prompt('Sodium mg per serving',log.sodium));if(q>0)M.updateLog(state,edit,{quantity:q,calories:cal,protein,sodium});persist();}if(del&&confirm('Delete this food entry?')){M.deleteLog(state,del);persist();}};
$('clearData').onclick=()=>{if(confirm('Delete all preview data?')){Object.keys(localStorage).filter(key=>key===M.KEY||key.startsWith('dcr_')).forEach(key=>localStorage.removeItem(key));location.reload();}};
$('exportPng').onclick=()=>{const r=M.report(state,state.selectedDate),c=$('reportCanvas'),ctx=c.getContext('2d');c.width=1080;c.height=1450;ctx.fillStyle='#f4f6f7';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.roundRect(55,55,970,1320,35);ctx.fill();ctx.fillStyle='#1d2a32';ctx.font='800 56px system-ui';ctx.fillText('Daily Cut Report',95,145);ctx.font='30px system-ui';ctx.fillStyle='#63727b';ctx.fillText(r.date+' · offline preview',95,195);const rows=[['Verdict',r.verdict],['Steps',Math.round(r.steps||0).toLocaleString()],['Final burn',Math.round(r.burn)+' kcal'],['Food',Math.round(r.calories)+' kcal'],['Protein',Math.round(r.protein)+' g'],['Sodium',Math.round(r.sodium)+' mg'],['Estimated deficit',Math.round(r.deficit)+' kcal']];rows.forEach((row,i)=>{const y=300+i*115;ctx.fillStyle='#52616a';ctx.font='32px system-ui';ctx.fillText(row[0],95,y);ctx.fillStyle='#1d2a32';ctx.font='700 38px system-ui';ctx.textAlign='right';ctx.fillText(row[1],985,y);ctx.textAlign='left';});ctx.fillStyle='#63727b';ctx.font='27px system-ui';ctx.fillText((r.notes||'No notes.').slice(0,70),95,1160);ctx.fillText('Generated locally. No network requests.',95,1300);const a=document.createElement('a');a.download=`DailyCutReport_${r.date}.png`;a.href=c.toDataURL('image/png');a.click();};
loadReportForm();render();
