(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.DailyCutBackup=api;})(this,function(){
  const enc=new TextEncoder(),dec=new TextDecoder(),MAGIC=enc.encode('DCRBKP01'),ITERATIONS=600000;
  function concat(...arrays){const out=new Uint8Array(arrays.reduce((n,a)=>n+a.length,0));let offset=0;for(const a of arrays){out.set(a,offset);offset+=a.length;}return out;}
  function u32(value){const out=new Uint8Array(4);new DataView(out.buffer).setUint32(0,value);return out;}
  function makeHeader(salt,nonce){return concat(MAGIC,u32(1),u32(ITERATIONS),u32(salt.length),salt,u32(nonce.length),nonce);}
  async function key(password,salt,usage,iterations=ITERATIONS){const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,[usage]);}
  async function encrypt(payload,password){const salt=crypto.getRandomValues(new Uint8Array(16)),nonce=crypto.getRandomValues(new Uint8Array(12)),header=makeHeader(salt,nonce),derived=await key(password,salt,'encrypt'),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:header,tagLength:128},derived,enc.encode(JSON.stringify(payload))));return concat(header,cipher);}
  function readU32(bytes,offset){return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(offset);}
  async function decrypt(bytes,password){let o=0;for(let i=0;i<MAGIC.length;i++)if(bytes[o++]!==MAGIC[i])throw new Error('Not a DailyCutReport backup.');const version=readU32(bytes,o);o+=4;if(version!==1)throw new Error('Unsupported backup format.');const iterations=readU32(bytes,o);o+=4;if(iterations<100000||iterations>1500000)throw new Error('Invalid backup key settings.');const saltLength=readU32(bytes,o);o+=4;if(saltLength<16||saltLength>64)throw new Error('Invalid backup salt.');const salt=bytes.slice(o,o+saltLength);o+=saltLength;const nonceLength=readU32(bytes,o);o+=4;if(nonceLength!==12)throw new Error('Invalid backup nonce.');const nonce=bytes.slice(o,o+nonceLength);o+=nonceLength;const header=bytes.slice(0,o),derived=await key(password,salt,'decrypt',iterations),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:nonce,additionalData:header,tagLength:128},derived,bytes.slice(o));return JSON.parse(dec.decode(plain));}
  return{encrypt,decrypt};
});
