(function(root,factory){const catalog=typeof module==='object'&&module.exports?require('./catalog.js'):root.DailyCutCatalog;const api=factory(catalog||[]);if(typeof module==='object'&&module.exports)module.exports=api;else root.DailyCutModel=api;})(this,function(catalog){
  const KEY='dcr_v4',OLD_KEY='dcr_v3';
  const number=value=>{const parsed=Number(String(value??'').replace(',','.'));return Number.isFinite(parsed)?parsed:0;};
  const optional=value=>String(value??'').trim()===''?null:number(value);
  const localDate=date=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;};
  const uuid=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const defaultSettings=()=>({goalMode:'CALORIE',calories:1850,expectedBurnCalories:2300,desiredDeficitCalories:450,protein:120,sodium:2000,carbs:150,fat:60,sugar:50,fiber:15,saturated:15,currencyCode:'TWD',dailyBudgetMicros:0});
  function empty(today){return{version:4,selectedDate:today,reports:{},products:{},logs:[],nextLogId:1,settings:defaultSettings()};}
  const plannerDefaults=p=>({...p,includeInPlanner:p.includeInPlanner??true,plannerItemType:p.plannerItemType==='DRINK'?'DRINK':'FOOD',alwaysIncludeInPlanner:p.alwaysIncludeInPlanner??false});
  function seed(state){for(const product of catalog)if(!state.products[product.productId])state.products[product.productId]=plannerDefaults({...product,purchasePriceMicros:null,purchaseUnitServings:1,updatedAt:Date.now()});for(const [id,p] of Object.entries(state.products))state.products[id]=plannerDefaults(p);for(const log of state.logs)log.excludeCostFromBudget=log.excludeCostFromBudget??false;return state;}
  function upgrade(old,today){const state=empty((old.selectedDate||today)>today?today:(old.selectedDate||today));state.reports=old.reports||{};state.settings={...defaultSettings(),...(old.settings||{})};for(const [key,p] of Object.entries(old.products||{})){const productId=p.productId||key,barcode=/^\d{8,14}$/.test(p.barcode||'')?p.barcode:null;state.products[productId]=plannerDefaults({...p,productId,barcode,purchasePriceMicros:p.purchasePriceMicros??null,purchaseUnitServings:number(p.purchaseUnitServings)||1});}state.logs=(old.logs||[]).map(log=>({...log,productId:log.productId||log.barcode||null,barcode:/^\d{8,14}$/.test(log.barcode||'')?log.barcode:null,catalogCostPerServingMicros:log.catalogCostPerServingMicros??null,actualPaidTotalMicros:log.actualPaidTotalMicros??null,excludeCostFromBudget:log.excludeCostFromBudget??false}));state.nextLogId=old.nextLogId||Math.max(0,...state.logs.map(x=>x.id))+1;return seed(state);}
  function migrate(storage,now=new Date()){
    const today=localDate(now),raw=storage.getItem(KEY);if(raw){try{const parsed=JSON.parse(raw);if(parsed.version===4)return seed({...parsed,settings:{...defaultSettings(),...(parsed.settings||{})}});}catch(_){}}
    for(const oldKey of [OLD_KEY,'dcr_v2']){const oldRaw=storage.getItem(oldKey);if(oldRaw){try{const old=JSON.parse(oldRaw);if(old.version===3||old.version===2){const state=upgrade(old,today);storage.setItem(KEY,JSON.stringify(state));return state;}}catch(_){}}}
    const state=empty(today),oldDate=storage.getItem('dcr_date')||today,hasLegacy=['steps','burn','food','protein','sodium','notes'].some(k=>storage.getItem('dcr_'+k)!==null);if(hasLegacy){state.selectedDate=oldDate>today?today:oldDate;state.reports[state.selectedDate]={steps:number(storage.getItem('dcr_steps')),distance:0,burn:optional(storage.getItem('dcr_burn')),foodOverride:optional(storage.getItem('dcr_food')),proteinOverride:optional(storage.getItem('dcr_protein')),sodiumOverride:optional(storage.getItem('dcr_sodium')),notes:storage.getItem('dcr_notes')||''};}seed(state);storage.setItem(KEY,JSON.stringify(state));return state;
  }
  function save(storage,state){storage.setItem(KEY,JSON.stringify(state));}
  function totals(state,date){return state.logs.filter(x=>x.date===date).reduce((t,x)=>{const q=number(x.quantity);t.entries++;for(const key of ['calories','protein','sodium','carbs','fat','sugar','fiber','saturated'])t[key]+=number(x[key])*q;return t;},{entries:0,calories:0,protein:0,sodium:0,carbs:0,fat:0,sugar:0,fiber:0,saturated:0});}
  function report(state,date){const stored=state.reports[date]||{},food=totals(state,date),burn=stored.burn??0,calories=food.calories,deficit=burn-calories;return{...stored,date,food,burn,calories,protein:food.protein,sodium:food.sodium,deficit,verdict:burn<=0?'Burn data unavailable':deficit>=300?'Cut day':deficit<=-200?'Surplus day':'Maintenance-ish'};}
  function upsertProduct(state,product){const productId=product.productId||uuid(),barcode=String(product.barcode||'').trim()||null;if(barcode&&Object.values(state.products).some(p=>p.productId!==productId&&p.barcode===barcode))throw new Error('Barcode is already assigned.');const saved=state.products[productId]=plannerDefaults({...product,productId,barcode,purchasePriceMicros:product.purchasePriceMicros??null,purchaseUnitServings:number(product.purchaseUnitServings)||1,updatedAt:Date.now()});if(saved.alwaysIncludeInPlanner&&!saved.includeInPlanner)throw new Error('A fixed item must be enabled for planning.');state.logs=state.logs.map(log=>log.productId!==productId?log:{...log,barcode:saved.barcode,name:saved.name,brand:saved.brand,servingLabel:saved.servingLabel,calories:number(saved.calories),protein:number(saved.protein),sodium:number(saved.sodium),carbs:number(saved.carbs),fat:number(saved.fat),sugar:number(saved.sugar),fiber:number(saved.fiber),saturated:number(saved.saturated),extras:saved.extras||[]});return saved;}
  function findBarcode(state,barcode){return Object.values(state.products).find(p=>p.barcode===String(barcode).trim())||null;}
  function addLog(state,date,product,quantity,actualPaidTotalMicros=null,excludeCostFromBudget=false,mealId=null,mealName=null){const q=number(quantity)||1,unit=number(product.purchaseUnitServings)||1,catalogCost=product.purchasePriceMicros==null?null:Math.round(number(product.purchasePriceMicros)/unit);const log={id:state.nextLogId++,date,quantity:q,...product,productId:product.productId||null,barcode:product.barcode||null,catalogCostPerServingMicros:catalogCost,actualPaidTotalMicros,excludeCostFromBudget,mealId,mealName};state.logs.push(log);return log;}
  function allocateBulkTotal(items,total){if(total==null)return items.map(()=>null);if(total===0)return items.map(()=>0);const catalog=items.map(({product,quantity})=>product.purchasePriceMicros==null||number(product.purchaseUnitServings)<=0?null:number(product.purchasePriceMicros)*number(quantity)/number(product.purchaseUnitServings)),weights=catalog.every(x=>x!=null)&&catalog.reduce((a,x)=>a+x,0)>0?catalog:items.map(x=>Math.max(0,number(x.quantity))),sum=weights.reduce((a,x)=>a+x,0)||items.length,effective=weights.some(x=>x>0)?weights:items.map(()=>1),raw=effective.map(x=>total*x/sum),allocated=raw.map(Math.floor);let remaining=total-allocated.reduce((a,x)=>a+x,0);const order=raw.map((x,i)=>({i,f:x-allocated[i]})).sort((a,b)=>b.f-a.f||a.i-b.i);for(let i=0;remaining>0;i++,remaining--)allocated[order[i%order.length].i]++;return allocated;}
  function addBulkPurchase(state,date,label,items,actualPaidTotalMicros=null,excludeCostFromBudget=false){if(items.length<2)throw new Error('Choose at least two items.');const id=uuid(),allocations=allocateBulkTotal(items,actualPaidTotalMicros),group=String(label||'').trim()||'Bulk purchase';return items.map((item,index)=>addLog(state,date,item.product,item.quantity,allocations[index],excludeCostFromBudget,id,group));}
  function updateLog(state,id,changes){const index=state.logs.findIndex(x=>x.id===id);if(index>=0)state.logs[index]={...state.logs[index],...changes};return state.logs[index]||null;}
  function deleteLog(state,id){state.logs=state.logs.filter(x=>x.id!==id);}
  function spending(state,date){return state.logs.filter(x=>x.date===date).reduce((t,x)=>{if(x.excludeCostFromBudget)return t;const cost=x.actualPaidTotalMicros??(x.catalogCostPerServingMicros==null?null:Math.round(x.catalogCostPerServingMicros*number(x.quantity)));if(cost==null)t.unknownEntries++;else t.knownTotalMicros+=cost;return t;},{knownTotalMicros:0,unknownEntries:0,budgetMicros:state.settings.dailyBudgetMicros||0});}
  function effectiveCalories(settings){return settings.goalMode==='DEFICIT'?number(settings.expectedBurnCalories)-number(settings.desiredDeficitCalories):number(settings.calories);}
  function plan(state,date){
    const consumed=totals(state,date),spent=spending(state,date),s=state.settings;
    const target={calories:effectiveCalories(s),protein:number(s.protein),sodium:number(s.sodium),carbs:number(s.carbs),fat:number(s.fat),sugar:number(s.sugar),fiber:number(s.fiber),saturated:number(s.saturated)};
    const all=Object.values(state.products),eligible=all.filter(p=>p.includeInPlanner!==false).sort((a,b)=>a.productId.localeCompare(b.productId));
    const excludedFromPlanningProducts=all.length-eligible.length,unpricedProducts=eligible.filter(p=>p.purchasePriceMicros==null).length;
    const base={items:[],nutrition:{calories:0,protein:0,sodium:0,carbs:0,fat:0,sugar:0,fiber:0,saturated:0},knownCost:0,unknownCosts:0,units:0,drinks:0};
    const add=(current,p,units,fixed=false)=>{const servings=number(p.purchaseUnitServings)*units,known=p.purchasePriceMicros==null?0:number(p.purchasePriceMicros)*units,nutrition=Object.fromEntries(Object.keys(target).map(k=>[k,number(p[k])*servings]));return{items:[...current.items,{productId:p.productId,name:p.name,purchaseUnits:units,servings,costMicros:p.purchasePriceMicros==null?null:known,fixed,itemType:p.plannerItemType||'FOOD'}],nutrition:Object.fromEntries(Object.keys(target).map(k=>[k,number(current.nutrition[k])+nutrition[k]])),knownCost:current.knownCost+known,unknownCosts:current.unknownCosts+(p.purchasePriceMicros==null?1:0),units:current.units+units,drinks:current.drinks+(p.plannerItemType==='DRINK'?units:0)};};
    const projected=x=>Object.fromEntries(Object.keys(target).map(k=>[k,number(consumed[k])+number(x.nutrition[k])]));
    const signature=x=>x.items.map(i=>`${i.productId}:${i.purchaseUnits}`).join('|');
    const ratio=(value,goal)=>goal>0?value/goal:0,over=(actual,goal)=>goal>0?Math.max(0,(actual-goal)/goal):(actual>0?actual:0),shortfall=(actual,goal)=>goal>0?Math.max(0,(goal-actual)/goal):0;
    const delta=(label,actual,goal,upper)=>{const percent=goal>0?(actual-goal)/goal*100:(actual===0?0:Infinity),within=label==='Calories'?Math.abs(percent)<=10:upper?percent<=10:percent>=-10;return{label,actual,target:goal,percentDifference:percent,withinTolerance:within};};
    const deltas=(n,cost)=>[delta('Calories',n.calories,target.calories,true),delta('Protein',n.protein,target.protein,false),delta('Fiber',n.fiber,target.fiber,false),delta('Sodium',n.sodium,target.sodium,true),delta('Carbs',n.carbs,target.carbs,true),delta('Fat',n.fat,target.fat,true),delta('Sugar',n.sugar,target.sugar,true),delta('Saturated fat',n.saturated,target.saturated,true),delta('Budget',cost/1e6,number(s.dailyBudgetMicros)/1e6,true)];
    const complete=x=>deltas(projected(x),spent.knownTotalMicros+x.knownCost).every(d=>d.withinTolerance);
    const toPlan=(x,mode='STRICT')=>{const n=projected(x),cost=spent.knownTotalMicros+x.knownCost,allDeltas=deltas(n,cost);return{items:x.items,nutrition:n,totalCostMicros:x.knownCost,projectedSpendingMicros:cost,withinBudget:s.dailyBudgetMicros>0&&cost<=s.dailyBudgetMicros,completeFit:complete(x),minimumTargetFallback:mode==='UNRESTRICTED_MINIMUM',mode,unknownCostItems:x.unknownCosts,unmetMinimums:allDeltas.filter(d=>(d.label==='Protein'||d.label==='Fiber')&&d.actual<d.target),deltas:allDeltas};};
    const result=(plans,message,blockingViolations=[])=>({plans,unpricedProducts,excludedFromPlanningProducts,spendingIncomplete:spent.unknownEntries>0||plans.some(p=>p.unknownCostItems>0),message,blockingViolations});
    const compareTuple=(a,b)=>{for(let i=0;i<a.length;i++){if(a[i]<b[i])return-1;if(a[i]>b[i])return 1;}return 0;};

    const minimumScore=x=>{const n=projected(x),protein=shortfall(n.protein,target.protein),fiber=shortfall(n.fiber,target.fiber),misses=(protein>0?1:0)+(fiber>0?1:0);const upperDamage=['sodium','carbs','fat','sugar','saturated'].reduce((sum,k)=>sum+Math.max(0,over(n[k],target[k])-over(consumed[k],target[k])),0);return[misses,protein+fiber,x.nutrition.calories,upperDamage,x.unknownCosts>0?1:0,x.knownCost,x.items.length,signature(x)];};
    const usefulUnits=(remaining,perUnit)=>Math.max(1,Math.min(1000000,Math.ceil(remaining/perUnit)));
    const quantityOptions=(current,p)=>{const n=projected(current),bounds=[];const proteinPer=number(p.protein)*number(p.purchaseUnitServings),fiberPer=number(p.fiber)*number(p.purchaseUnitServings);if(target.protein>n.protein&&proteinPer>0)bounds.push(usefulUnits(target.protein-n.protein,proteinPer));if(target.fiber>n.fiber&&fiberPer>0)bounds.push(usefulUnits(target.fiber-n.fiber,fiberPer));if(!bounds.length)return[0];const values=new Set([0,1]);for(const boundary of bounds){values.add(boundary);if(boundary>1)values.add(boundary-1);for(let divisor=2;divisor<=4;divisor++)values.add(Math.max(1,Math.ceil(boundary/divisor)));}return[...values].sort((a,b)=>a-b);};
    const fallback=()=>{const needsProtein=target.protein>0&&consumed.protein<target.protein,needsFiber=target.fiber>0&&consumed.fiber<target.fiber;if(!needsProtein&&!needsFiber)return null;const candidates=eligible.filter(p=>number(p.purchaseUnitServings)>0&&((needsProtein&&number(p.protein)>0)||(needsFiber&&number(p.fiber)>0)));if(!candidates.length)return null;let beam=[base];for(const p of candidates){const expanded=[];for(const current of beam)for(const units of quantityOptions(current,p))expanded.push(units===0?current:add(current,p,units));beam=[...new Map(expanded.map(x=>[signature(x),x])).values()].sort((a,b)=>compareTuple(minimumScore(a),minimumScore(b))).slice(0,48);}const best=beam.filter(x=>x.items.length).filter(x=>{const n=projected(x);return(needsProtein&&n.protein>consumed.protein)||(needsFiber&&n.fiber>consumed.fiber);}).sort((a,b)=>compareTuple(minimumScore(a),minimumScore(b)))[0];return best?toPlan(best,'UNRESTRICTED_MINIMUM'):null;};
    const fallbackResult=(reason,strictViolations=[])=>{const best=fallback(),message=best?`${reason} Showing one unrestricted minimum-target option; fixed-item, drink, budget, calorie, upper-nutrient, and strict quantity limits are ignored.`:`${reason} No eligible product can improve an unmet protein or fiber minimum.`;const fallbackViolations=best?[...best.unmetMinimums,...best.deltas.filter(d=>!d.withinTolerance)]:[];return result(best?[best]:[],message,[...new Map([...strictViolations,...fallbackViolations].map(x=>[x.label,x])).values()]);};

    const fixed=eligible.filter(p=>p.alwaysIncludeInPlanner),strictProducts=eligible.filter(p=>!p.alwaysIncludeInPlanner&&p.purchasePriceMicros!=null&&number(p.purchaseUnitServings)>0),fixedState=fixed.reduce((current,p)=>add(current,p,1,true),base);
    if(number(s.dailyBudgetMicros)<=0)return fallbackResult('Strict planning requires a daily budget.');
    if(fixed.some(p=>p.purchasePriceMicros==null))return fallbackResult('Strict planning requires prices for fixed items.');
    if(fixed.length>20)return fallbackResult('Strict planning allows at most 20 fixed purchase units.');
    if(fixed.filter(p=>p.plannerItemType==='DRINK').length>2)return fallbackResult('Strict planning allows at most 2 fixed drinks.');
    if(spent.knownTotalMicros>s.dailyBudgetMicros*1.1)return fallbackResult('Current spending already exceeds the strict budget ceiling.');
    const valid=x=>{const n=projected(x);return x.units<=20&&x.drinks<=2&&n.calories<=target.calories*1.1&&n.sodium<=target.sodium*1.1&&n.carbs<=target.carbs*1.1&&n.fat<=target.fat*1.1&&n.sugar<=target.sugar*1.1&&n.saturated<=target.saturated*1.1&&spent.knownTotalMicros+x.knownCost<=s.dailyBudgetMicros*1.1;};
    const score=x=>{const n=projected(x);return Math.abs(ratio(n.calories,target.calories)-1)+shortfall(n.protein,target.protein)+shortfall(n.fiber,target.fiber)+['sodium','carbs','fat','sugar','saturated'].reduce((sum,k)=>sum+over(n[k],target[k]),0)+over(spent.knownTotalMicros+x.knownCost,s.dailyBudgetMicros)*2;};
    if(!valid(fixedState)){const violations=deltas(projected(fixedState),spent.knownTotalMicros+fixedState.knownCost).filter(d=>!d.withinTolerance&&d.label!=='Protein'&&d.label!=='Fiber'&&d.percentDifference>10);return fallbackResult('Current values or fixed items exceed a strict nutrition or budget ceiling.',violations);}
    let beam=[fixedState];for(const p of strictProducts){const expanded=[];for(const current of beam)for(let units=0;units<=6&&current.units+units<=20;units++){if(p.plannerItemType==='DRINK'&&current.drinks+units>2)break;const next=units===0?current:add(current,p,units);if(valid(next))expanded.push(next);}beam=[...new Map(expanded.map(x=>[signature(x),x])).values()].sort((a,b)=>score(a)-score(b)||a.knownCost-b.knownCost||signature(a).localeCompare(signature(b))).slice(0,200);}
    const strictPlans=beam.filter(x=>x.items.length&&complete(x)).sort((a,b)=>score(a)-score(b)||a.knownCost-b.knownCost||signature(a).localeCompare(signature(b))).slice(0,3).map(x=>toPlan(x));
    return strictPlans.length?result(strictPlans,null):fallbackResult('No complete strict plan fits the current values and limits.');
  }
  return{KEY,OLD_KEY,number,optional,localDate,empty,migrate,save,seed,totals,report,upsertProduct,findBarcode,addLog,addBulkPurchase,allocateBulkTotal,updateLog,deleteLog,spending,effectiveCalories,plan,defaultSettings,uuid,catalog};
});
