(function(root,factory){const catalog=typeof module==='object'&&module.exports?require('./catalog.js'):root.DailyCutCatalog;const api=factory(catalog||[]);if(typeof module==='object'&&module.exports)module.exports=api;else root.DailyCutModel=api;})(this,function(catalog){
  const KEY='dcr_v4',OLD_KEY='dcr_v3';
  const number=value=>{const parsed=Number(String(value??'').replace(',','.'));return Number.isFinite(parsed)?parsed:0;};
  const optional=value=>String(value??'').trim()===''?null:number(value);
  const localDate=date=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;};
  const uuid=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const defaultSettings=()=>({goalMode:'CALORIE',calories:1850,expectedBurnCalories:2300,desiredDeficitCalories:450,protein:120,sodium:2000,carbs:150,fat:60,sugar:50,fiber:15,saturated:15,currencyCode:'TWD',dailyBudgetMicros:0});
  function empty(today){return{version:4,selectedDate:today,reports:{},products:{},logs:[],nextLogId:1,settings:defaultSettings()};}
  const plannerDefaults=p=>({...p,includeInPlanner:p.includeInPlanner??true,plannerItemType:p.plannerItemType==='DRINK'?'DRINK':'FOOD',alwaysIncludeInPlanner:p.alwaysIncludeInPlanner??false});
  function seed(state){for(const product of catalog)if(!state.products[product.productId])state.products[product.productId]=plannerDefaults({...product,purchasePriceMicros:null,purchaseUnitServings:1,updatedAt:Date.now()});for(const [id,p] of Object.entries(state.products))state.products[id]=plannerDefaults(p);for(const log of state.logs)log.excludeCostFromBudget=log.excludeCostFromBudget??false;return state;}
  function upgrade(old,today){const state=empty((old.selectedDate||today)>today?today:(old.selectedDate||today));state.reports=old.reports||{};state.settings={...defaultSettings(),...(old.settings||{})};for(const [key,p] of Object.entries(old.products||{})){const productId=p.productId||key,barcode=/^\d{8,14}$/.test(p.barcode||'')?p.barcode:null;state.products[productId]=plannerDefaults({...p,productId,barcode,purchasePriceMicros:p.purchasePriceMicros??null,purchaseUnitServings:number(p.purchaseUnitServings)||1});}state.logs=(old.logs||[]).map(log=>({...log,productId:log.productId||log.barcode||null,barcode:/^\d{8,14}$/.test(log.barcode||'')?log.barcode:null,catalogCostPerServingMicros:log.catalogCostPerServingMicros??null,actualPaidTotalMicros:log.actualPaidTotalMicros??null,excludeCostFromBudget:log.excludeCostFromBudget??false}));state.nextLogId=old.nextLogId||Math.max(0,...state.logs.map(x=>x.id))+1;return seed(state);}
  function migrate(storage,now=new Date()){
    const today=localDate(now),raw=storage.getItem(KEY);if(raw){try{const parsed=JSON.parse(raw);if(parsed.version===4)return seed({...parsed,settings:{...defaultSettings(),...(parsed.settings||{})}});}catch(_){}}
    for(const oldKey of [OLD_KEY,'dcr_v2']){const oldRaw=storage.getItem(oldKey);if(oldRaw){try{const old=JSON.parse(oldRaw);if(old.version===3||old.version===2){const state=upgrade(old,today);storage.setItem(KEY,JSON.stringify(state));return state;}}catch(_){}}}
    const state=empty(today),oldDate=storage.getItem('dcr_date')||today,hasLegacy=['steps','burn','food','protein','sodium','notes'].some(k=>storage.getItem('dcr_'+k)!==null);if(hasLegacy){state.selectedDate=oldDate>today?today:oldDate;state.reports[state.selectedDate]={steps:number(storage.getItem('dcr_steps')),distance:0,burn:optional(storage.getItem('dcr_burn')),foodOverride:optional(storage.getItem('dcr_food')),proteinOverride:optional(storage.getItem('dcr_protein')),sodiumOverride:optional(storage.getItem('dcr_sodium')),notes:storage.getItem('dcr_notes')||''};}seed(state);storage.setItem(KEY,JSON.stringify(state));return state;
  }
  function save(storage,state){storage.setItem(KEY,JSON.stringify(state));}
  function totals(state,date){return state.logs.filter(x=>x.date===date).reduce((t,x)=>{const q=number(x.quantity);t.entries++;for(const key of ['calories','protein','sodium','carbs','fat','sugar','fiber','saturated'])t[key]+=number(x[key])*q;return t;},{entries:0,calories:0,protein:0,sodium:0,carbs:0,fat:0,sugar:0,fiber:0,saturated:0});}
  function report(state,date){const stored=state.reports[date]||{},food=totals(state,date),burn=stored.burn??0,calories=food.calories,deficit=burn-calories;return{...stored,date,food,burn,calories,protein:food.protein,sodium:food.sodium,deficit,verdict:burn<=0?'Burn data unavailable':deficit>=300?'Cut day':deficit<=-200?'Surplus day':'Maintenance-ish'};}
  function upsertProduct(state,product){const productId=product.productId||uuid(),barcode=String(product.barcode||'').trim()||null;if(barcode&&Object.values(state.products).some(p=>p.productId!==productId&&p.barcode===barcode))throw new Error('Barcode is already assigned.');const saved=state.products[productId]=plannerDefaults({...product,productId,barcode,purchasePriceMicros:product.purchasePriceMicros??null,purchaseUnitServings:number(product.purchaseUnitServings)||1,updatedAt:Date.now()});if(saved.alwaysIncludeInPlanner&&!saved.includeInPlanner)throw new Error('A fixed item must be enabled for planning.');state.logs=state.logs.map(log=>log.productId!==productId?log:{...log,barcode:saved.barcode,name:saved.name,brand:saved.brand,servingLabel:saved.servingLabel,calories:number(saved.calories),protein:number(saved.protein),sodium:number(saved.sodium),carbs:number(saved.carbs),fat:number(saved.fat),sugar:number(saved.sugar),fiber:number(saved.fiber),saturated:number(saved.saturated),extras:saved.extras||[]});return saved;}
  function findBarcode(state,barcode){return Object.values(state.products).find(p=>p.barcode===String(barcode).trim())||null;}
  function addLog(state,date,product,quantity,actualPaidTotalMicros=null,excludeCostFromBudget=false){const q=number(quantity)||1,unit=number(product.purchaseUnitServings)||1,catalogCost=product.purchasePriceMicros==null?null:Math.round(number(product.purchasePriceMicros)/unit);const log={id:state.nextLogId++,date,quantity:q,...product,productId:product.productId||null,barcode:product.barcode||null,catalogCostPerServingMicros:catalogCost,actualPaidTotalMicros,excludeCostFromBudget};state.logs.push(log);return log;}
  function updateLog(state,id,changes){const index=state.logs.findIndex(x=>x.id===id);if(index>=0)state.logs[index]={...state.logs[index],...changes};return state.logs[index]||null;}
  function deleteLog(state,id){state.logs=state.logs.filter(x=>x.id!==id);}
  function spending(state,date){return state.logs.filter(x=>x.date===date).reduce((t,x)=>{if(x.excludeCostFromBudget)return t;const cost=x.actualPaidTotalMicros??(x.catalogCostPerServingMicros==null?null:Math.round(x.catalogCostPerServingMicros*number(x.quantity)));if(cost==null)t.unknownEntries++;else t.knownTotalMicros+=cost;return t;},{knownTotalMicros:0,unknownEntries:0,budgetMicros:state.settings.dailyBudgetMicros||0});}
  function effectiveCalories(settings){return settings.goalMode==='DEFICIT'?number(settings.expectedBurnCalories)-number(settings.desiredDeficitCalories):number(settings.calories);}
  function plan(state,date){
    const consumed=totals(state,date),spent=spending(state,date),s=state.settings,target={calories:effectiveCalories(s),protein:number(s.protein),sodium:number(s.sodium),carbs:number(s.carbs),fat:number(s.fat),sugar:number(s.sugar),fiber:number(s.fiber),saturated:number(s.saturated)},all=Object.values(state.products),eligible=all.filter(p=>p.includeInPlanner!==false),excludedFromPlanningProducts=all.length-eligible.length,excludedUnpricedProducts=eligible.filter(p=>p.purchasePriceMicros==null).length,fixed=eligible.filter(p=>p.alwaysIncludeInPlanner).sort((a,b)=>a.productId.localeCompare(b.productId)),products=eligible.filter(p=>!p.alwaysIncludeInPlanner&&p.purchasePriceMicros!=null&&number(p.purchaseUnitServings)>0).sort((a,b)=>a.productId.localeCompare(b.productId));
    const result=(plans,message)=>({plans,excludedUnpricedProducts,excludedFromPlanningProducts,spendingIncomplete:spent.unknownEntries>0,message});
    if(number(s.dailyBudgetMicros)<=0)return result([],'Set a daily budget first.');
    if(fixed.some(p=>p.purchasePriceMicros==null))return result([],'Add prices to fixed planner items before planning.');
    if(fixed.filter(p=>p.plannerItemType==='DRINK').length>2)return result([],'Too many fixed drinks: planning allows at most 2.');
    const base={items:[],nutrition:{calories:0,protein:0,sodium:0,carbs:0,fat:0,sugar:0,fiber:0,saturated:0},cost:0,units:0,drinks:0};
    const add=(b,p,units,isFixed=false)=>{const servings=number(p.purchaseUnitServings)*units,cost=number(p.purchasePriceMicros)*units,nutrition=Object.fromEntries(Object.keys(target).map(k=>[k,number(p[k])*servings]));return{items:[...b.items,{productId:p.productId,name:p.name,purchaseUnits:units,servings,costMicros:cost,fixed:isFixed,itemType:p.plannerItemType||'FOOD'}],nutrition:Object.fromEntries(Object.keys(target).map(k=>[k,number(b.nutrition[k])+nutrition[k]])),cost:b.cost+cost,units:b.units+units,drinks:b.drinks+(p.plannerItemType==='DRINK'?units:0)};};
    let beam=fixed.reduce((b,p)=>add(b,p,1,true),base);const projected=x=>Object.fromEntries(Object.keys(target).map(k=>[k,number(consumed[k])+number(x.nutrition[k])]));const valid=x=>{const n=projected(x);return x.units<=20&&x.drinks<=2&&n.calories<=target.calories*1.1&&n.sodium<=target.sodium*1.1&&n.carbs<=target.carbs*1.1&&n.fat<=target.fat*1.1&&n.sugar<=target.sugar*1.1&&n.saturated<=target.saturated*1.1&&spent.knownTotalMicros+x.cost<=s.dailyBudgetMicros*1.1;};const score=x=>{const n=projected(x),over=k=>Math.max(0,(n[k]-target[k])/Math.max(1,target[k]));return Math.abs(n.calories-target.calories)/target.calories+Math.max(0,(target.protein-n.protein)/Math.max(1,target.protein))+Math.max(0,(target.fiber-n.fiber)/Math.max(1,target.fiber))+['sodium','carbs','fat','sugar','saturated'].reduce((a,k)=>a+over(k),0)+Math.max(0,(spent.knownTotalMicros+x.cost-s.dailyBudgetMicros)/s.dailyBudgetMicros)*2;};
    if(!valid(beam))return result([],'Fixed planner items exceed a nutrition or budget ceiling.');beam=[beam];for(const p of products){const expanded=[];for(const b of beam)for(let units=0;units<=6&&b.units+units<=20;units++){if(p.plannerItemType==='DRINK'&&b.drinks+units>2)break;const next=units===0?b:add(b,p,units);if(valid(next))expanded.push(next);}beam=expanded.sort((a,b)=>score(a)-score(b)||a.cost-b.cost).slice(0,200);}const plans=beam.filter(x=>x.items.length).sort((a,b)=>score(a)-score(b)||a.cost-b.cost).slice(0,3).map(x=>({items:x.items,nutrition:projected(x),totalCostMicros:x.cost,projectedSpendingMicros:spent.knownTotalMicros+x.cost,withinBudget:spent.knownTotalMicros+x.cost<=s.dailyBudgetMicros}));return result(plans,plans.length?null:'No combination stays within the 10% ceilings.');}
  return{KEY,OLD_KEY,number,optional,localDate,empty,migrate,save,seed,totals,report,upsertProduct,findBarcode,addLog,updateLog,deleteLog,spending,effectiveCalories,plan,defaultSettings,uuid,catalog};
});
