const test=require('node:test');const assert=require('node:assert/strict');const M=require('./model.js');
const Backup=require('./backup.js');
const fs=require('node:fs'),path=require('node:path');
function storage(initial={}){const data={...initial};return{getItem:k=>Object.hasOwn(data,k)?data[k]:null,setItem:(k,v)=>data[k]=String(v),removeItem:k=>delete data[k],data};}
test('migrates legacy values once',()=>{const s=storage({dcr_date:'2026-01-02',dcr_steps:'1234',dcr_burn:'2100',dcr_food:'1800'});const state=M.migrate(s,new Date('2026-01-03T12:00:00'));assert.equal(state.version,3);assert.equal(state.reports['2026-01-02'].steps,1234);assert.equal(M.migrate(s).reports['2026-01-02'].burn,2100);});
test('migrates v2 products and adds the bundled catalog without overwriting',()=>{const old={version:2,selectedDate:'2026-01-03',reports:{},products:{CUSTOM:{barcode:'CUSTOM',name:'Edited Base',calories:1}},logs:[],nextLogId:1};const s=storage({dcr_v2:JSON.stringify(old)}),state=M.migrate(s,new Date('2026-01-03T12:00:00'));assert.equal(state.products.CUSTOM.barcode,null);assert.equal(state.products.CUSTOM.name,'Edited Base');assert.equal(Object.keys(state.products).length,18);assert.equal(state.products['4711089912108'].barcode,'4711089912108');});
test('calculates food totals and standard verdict thresholds',()=>{const state=M.empty('2026-01-03');state.reports['2026-01-03']={burn:2000};const p={barcode:'1',name:'Food',calories:900,protein:30,sodium:100,carbs:0,fat:0,sugar:0,fiber:0,saturated:0};M.addLog(state,'2026-01-03',p,2);const report=M.report(state,'2026-01-03');assert.equal(report.calories,1800);assert.equal(report.verdict,'Maintenance-ish');state.reports['2026-01-03'].burn=2100;assert.equal(M.report(state,'2026-01-03').verdict,'Cut day');});
test('updates and deletes daily log snapshots',()=>{const state=M.empty('2026-01-03');const log=M.addLog(state,'2026-01-03',{barcode:'1',name:'Food',calories:100,protein:1,sodium:2,carbs:0,fat:0,sugar:0,fiber:0,saturated:0},1);M.updateLog(state,log.id,{quantity:3});assert.equal(M.totals(state,'2026-01-03').calories,300);M.deleteLog(state,log.id);assert.equal(M.totals(state,'2026-01-03').entries,0);});
test('supports products without barcodes and rejects duplicate physical barcodes',()=>{const state=M.empty('2026-01-03');M.upsertProduct(state,{productId:'a',barcode:null,name:'Custom'});M.upsertProduct(state,{productId:'b',barcode:'4711089912108',name:'Retail'});assert.equal(M.findBarcode(state,'4711089912108').productId,'b');assert.throws(()=>M.upsertProduct(state,{productId:'c',barcode:'4711089912108',name:'Duplicate'}));});
test('encrypted browser backup authenticates password and payload',async()=>{const payload={schemaVersion:1,products:[{productId:'a'}]},password='correct horse';const encrypted=await Backup.encrypt(payload,password);assert.deepEqual(await Backup.decrypt(encrypted,password),payload);await assert.rejects(()=>Backup.decrypt(encrypted,'wrong password'));encrypted[encrypted.length-1]^=1;await assert.rejects(()=>Backup.decrypt(encrypted,password));});
test('Android and browser catalogs contain the same 17 stable IDs',()=>{const android=JSON.parse(fs.readFileSync(path.join(__dirname,'../app/src/main/assets/preloaded_products.json'),'utf8'));assert.equal(android.products.length,17);assert.equal(new Set(android.products.map(x=>x.id)).size,17);assert.deepEqual(new Set(android.products.map(x=>x.id)),new Set(M.catalog.map(x=>x.productId)));});
