(function(root,factory){const catalog=typeof module==='object'&&module.exports?require('./catalog.js'):root.DailyCutCatalog;const api=factory(catalog||[]);if(typeof module==='object'&&module.exports)module.exports=api;else root.DailyCutModel=api;})(this,function(catalog){
  const KEY='dcr_v4',OLD_KEY='dcr_v3';
  const number=value=>{const parsed=Number(String(value??'').replace(',','.'));return Number.isFinite(parsed)?parsed:0;};
  const optional=value=>String(value??'').trim()===''?null:number(value);
  const localDate=date=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;};
  const uuid=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const defaultSettings=()=>({goalMode:'CALORIE',calories:1850,expectedBurnCalories:2300,desiredDeficitCalories:450,protein:120,sodium:2000,carbs:150,fat:60,sugar:50,fiber:15,saturated:15,currencyCode:'TWD',dailyBudgetMicros:0});
  function empty(today){return{version:4,selectedDate:today,reports:{},products:{},logs:[],nextLogId:1,settings:defaultSettings()};}
  const plannerDefaults=p=>({...p,includeInPlanner:p.includeInPlanner??true,plannerItemType:p.plannerItemType==='DRINK'?'DRINK':'FOOD',alwaysIncludeInPlanner:p.alwaysIncludeInPlanner??false});
  function seed(state){for(const product of catalog)if(!state.products[product.productId])state.products[product.productId]=plannerDefaults({...product,purchasePriceMicros:null,purchaseUnitServings:1,updatedAt:Date.now()});for(const [id,p] of Object.entries(state.products))state.products[id]=plannerDefaults(p);for(const log of state.logs)log.excludeCostFromBudget=log.excludeCostFromBudget??false;return state;}
  function upgrade(old,today){const state=empty((old.selectedDate||today)>today?today:(old.selectedDate||today));state.reports=old.reports||{};state.settings={...defaultSettings(),...(old.settings||{})};for(const [key,p] of Object.entries(old.products||{})){const productId=p.productId||key,barcode=/^\d{8,14}$/.test(p.barcode||'')?p.barcode:null;state.products[productId]=plannerDefaults({...p,productId,barcode,purchasePriceMicros:p.purchasePriceMicros??null,purchaseUnitServings:number(p.purchaseUnitServings)||1});}state.logs=(old.logs||[]).map(log=>({...log,productId:log.productId||log.barcode||null,barcode:/^\d{8,14}$/.test(log.barcode||'')?log.barcode:null,catalogCostPerServingMicros:log.catalogCostPerServingMicros??null,actualPaidTotalMicros:log.actualPaidTotalMicros??null,excludeCostFromBudget:log.excludeCostFromBudget??false}));state.nextLogId=old.nextLogId||Math.max(0,...state.logs.map(x=>x.id))+1;return seed(state);}
  function migrate(storage,now=new Date()){
    const today=localDate(now),raw=storage.getItem(KEY);if(raw){try{const parsed=JSON.parse(raw);if(parsed.version===4)return seed({...parsed,settings:{...defaultSettings(),...(parsed.settings||{})}});}catch(_){}}
    for(const oldKey of [OLD_KEY,'dcr_v2']){const oldRaw=storage.getItem(oldKey);if(oldRaw){try{const old=JSON.parse(oldRaw);if(old.version===3||old.version===2){const state=upgrade(old,today);storage.setItem(KEY,JSON.stringify(state));return state;}}catch(_){}}}
    const state=empty(today),oldDate=storage.getItem('dcr_date')||today,hasLegacy=['steps','burn','food','protein','sodium','notes'].some(k=>storage.getItem('dcr_'+k)!==null);if(hasLegacy){state.selectedDate=oldDate>today?today:oldDate;state.reports[state.selectedDate]={steps:number(storage.getItem('dcr_steps')),distance:0,burn:optional(storage.getItem('dcr_burn')),foodOverride:optional(storage.getItem('dcr_food')),proteinOverride:optional(storage.getItem('dcr_protein')),sodiumOverride:optional(storage.getItem('dcr_sodium')),notes:storage.getItem('dcr_notes')||''};}seed(state);storage.setItem(KEY,JSON.stringify(state));return state;
  }
  function save(storage,state){storage.setItem(KEY,JSON.stringify(state));}
  function totals(state,date){return state.logs.filter(x=>x.date===date).reduce((t,x)=>{const q=number(x.quantity);t.entries++;for(const key of ['calories','protein','sodium','carbs','fat','sugar','fiber','saturated'])t[key]+=number(x[key])*q;return t;},{entries:0,calories:0,protein:0,sodium:0,carbs:0,fat:0,sugar:0,fiber:0,saturated:0});}
  function report(state,date){const stored=state.reports[date]||{},food=totals(state,date),burn=stored.burn??0,calories=food.calories,deficit=burn-calories;return{...stored,date,food,burn,calories,protein:food.protein,sodium:food.sodium,deficit,verdict:burn<=0?'Burn data unavailable':deficit>=300?'Cut day':deficit<=-200?'Surplus day':'Maintenance-ish'};}
  function upsertProduct(state,product){const productId=product.productId||uuid(),barcode=String(product.barcode||'').trim()||null;if(barcode&&Object.values(state.products).some(p=>p.productId!==productId&&p.barcode===barcode))throw new Error('Barcode is already assigned.');const saved=state.products[productId]=plannerDefaults({...product,productId,barcode,purchasePriceMicros:product.purchasePriceMicros??null,purchaseUnitServings:number(product.purchaseUnitServings)||1,updatedAt:Date.now()});if(saved.alwaysIncludeInPlanner&&!saved.includeInPlanner)throw new Error('A fixed item must be enabled for planning.');state.logs=state.logs.map(log=>log.productId!==productId?log:{...log,barcode:saved.barcode,name:saved.name,brand:saved.brand,servingLabel:saved.servingLabel,calories:number(saved.calories),protein:number(saved.protein),sodium:number(saved.sodium),carbs:number(saved.carbs),fat:number(saved.fat),sugar:number(saved.sugar),fiber:number(saved.fiber),saturated:number(saved.saturated),extras:saved.extras||[]});return saved;}
  function findBarcode(state,barcode){return Object.values(state.products).find(p=>p.barcode===String(barcode).trim())||null;}
  function addLog(state,date,product,quantity,actualPaidTotalMicros=null,excludeCostFromBudget=false,mealId=null,mealName=null){const q=number(quantity)||1,unit=number(product.purchaseUnitServings)||1,catalogCost=product.purchasePriceMicros==null?null:Math.round(number(product.purchasePriceMicros)/unit);const log={id:state.nextLogId++,date,quantity:q,...product,productId:product.productId||null,barcode:product.barcode||null,catalogCostPerServingMicros:catalogCost,actualPaidTotalMicros,excludeCostFromBudget,mealId,mealName};state.logs.push(log);return log;}
  function allocateBulkTotal(items,total){if(total==null)return items.map(()=>null);if(total===0)return items.map(()=>0);const catalog=items.map(({product,quantity})=>product.purchasePriceMicros==null||number(product.purchaseUnitServings)<=0?null:number(product.purchasePriceMicros)*number(quantity)/number(product.purchaseUnitServings)),weights=catalog.every(x=>x!=null)&&catalog.reduce((a,x)=>a+x,0)>0?catalog:items.map(x=>Math.max(0,number(x.quantity))),sum=weights.reduce((a,x)=>a+x,0)||items.length,effective=weights.some(x=>x>0)?weights:items.map(()=>1),raw=effective.map(x=>total*x/sum),allocated=raw.map(Math.floor);let remaining=total-allocated.reduce((a,x)=>a+x,0);const order=raw.map((x,i)=>({i,f:x-allocated[i]})).sort((a,b)=>b.f-a.f||a.i-b.i);for(let i=0;remaining>0;i++,remaining--)allocated[order[i%order.length].i]++;return allocated;}
  function addBulkPurchase(state,date,label,items,actualPaidTotalMicros=null,excludeCostFromBudget=false){if(items.length<2)throw new Error('Choose at least two items.');const id=uuid(),allocations=allocateBulkTotal(items,actualPaidTotalMicros),group=String(label||'').trim()||'Bulk purchase';return items.map((item,index)=>addLog(state,date,item.product,item.quantity,allocations[index],excludeCostFromBudget,id,group));}
  function updateLog(state,id,changes){const index=state.logs.findIndex(x=>x.id===id);if(index>=0)state.logs[index]={...state.logs[index],...changes};return state.logs[index]||null;}
  function deleteLog(state,id){state.logs=state.logs.filter(x=>x.id!==id);}
  function spending(state,date){return state.logs.filter(x=>x.date===date).reduce((t,x)=>{if(x.excludeCostFromBudget)return t;const cost=x.actualPaidTotalMicros??(x.catalogCostPerServingMicros==null?null:Math.round(x.catalogCostPerServingMicros*number(x.quantity)));if(cost==null)t.unknownEntries++;else t.knownTotalMicros+=cost;return t;},{knownTotalMicros:0,unknownEntries:0,budgetMicros:state.settings.dailyBudgetMicros||0});}
  function effectiveCalories(settings){return settings.goalMode==='DEFICIT'?number(settings.expectedBurnCalories)-number(settings.desiredDeficitCalories):number(settings.calories);}
  function plan(state,date){
    const consumed=totals(state,date),spent=spending(state,date),s=state.settings,target={calories:effectiveCalories(s),protein:number(s.protein),sodium:number(s.sodium),carbs:number(s.carbs),fat:number(s.fat),sugar:number(s.sugar),fiber:number(s.fiber),saturated:number(s.saturated)},all=Object.values(state.products),eligible=all.filter(p=>p.includeInPlanner!==false),excludedFromPlanningProducts=all.length-eligible.length,excludedUnpricedProducts=eligible.filter(p=>p.purchasePriceMicros==null).length,fixed=eligible.filter(p=>p.alwaysIncludeInPlanner).sort((a,b)=>a.productId.localeCompare(b.productId)),products=eligible.filter(p=>!p.alwaysIncludeInPlanner&&p.purchasePriceMicros!=null&&number(p.purchaseUnitServings)>0).sort((a,b)=>a.productId.localeCompare(b.productId));
    const result=(plans,message,blockingViolations=[])=>({plans,excludedUnpricedProducts,excludedFromPlanningProducts,spendingIncomplete:spent.unknownEntries>0,message,blockingViolations});
    if(number(s.dailyBudgetMicros)<=0)return result([],'Set a daily budget first.');
    if(fixed.some(p=>p.purchasePriceMicros==null))return result([],'Add prices to fixed planner items before planning.');
    if(fixed.filter(p=>p.plannerItemType==='DRINK').length>2)return result([],'Too many fixed drinks: planning allows at most 2.');
    const base={items:[],nutrition:{calories:0,protein:0,sodium:0,carbs:0,fat:0,sugar:0,fiber:0,saturated:0},cost:0,units:0,drinks:0};
    const add=(b,p,units,isFixed=false)=>{const servings=number(p.purchaseUnitServings)*units,cost=number(p.purchasePriceMicros)*units,nutrition=Object.fromEntries(Object.keys(target).map(k=>[k,number(p[k])*servings]));return{items:[...b.items,{productId:p.productId,name:p.name,purchaseUnits:units,servings,costMicros:cost,fixed:isFixed,itemType:p.plannerItemType||'FOOD'}],nutrition:Object.fromEntries(Object.keys(target).map(k=>[k,number(b.nutrition[k])+nutrition[k]])),cost:b.cost+cost,units:b.units+units,drinks:b.drinks+(p.plannerItemType==='DRINK'?units:0)};};
    const fixedState=fixed.reduce((b,p)=>add(b,p,1,true),base),projected=x=>Object.fromEntries(Object.keys(target).map(k=>[k,number(consumed[k])+number(x.nutrition[k])])),signature=x=>x.items.map(i=>`${i.productId}:${i.purchaseUnits}`).join('|'),over=(actual,goal)=>Math.max(0,(actual-goal)/Math.max(1,goal));
    const delta=(label,actual,goal,upper)=>{const percent=(actual-goal)/Math.max(1,goal)*100,within=label==='Calories'?Math.abs(percent)<=10:upper?percent<=10:percent>=-10;return{label,actual,target:goal,percentDifference:percent,withinTolerance:within};};
    const deltas=(n,cost)=>[delta('Calories',n.calories,target.calories,true),delta('Protein',n.protein,target.protein,false),delta('Fiber',n.fiber,target.fiber,false),delta('Sodium',n.sodium,target.sodium,true),delta('Carbs',n.carbs,target.carbs,true),delta('Fat',n.fat,target.fat,true),delta('Sugar',n.sugar,target.sugar,true),delta('Saturated fat',n.saturated,target.saturated,true),delta('Budget',cost/1e6,s.dailyBudgetMicros/1e6,true)];
    const valid=x=>{const n=projected(x);return x.units<=20&&x.drinks<=2&&n.calories<=target.calories*1.1&&n.sodium<=target.sodium*1.1&&n.carbs<=target.carbs*1.1&&n.fat<=target.fat*1.1&&n.sugar<=target.sugar*1.1&&n.saturated<=target.saturated*1.1&&spent.knownTotalMicros+x.cost<=s.dailyBudgetMicros*1.1;};
    const score=x=>{const n=projected(x);return Math.abs(n.calories-target.calories)/Math.max(1,target.calories)+Math.max(0,(target.protein-n.protein)/Math.max(1,target.protein))+Math.max(0,(target.fiber-n.fiber)/Math.max(1,target.fiber))+['sodium','carbs','fat','sugar','saturated'].reduce((a,k)=>a+over(n[k],target[k]),0)+over(spent.knownTotalMicros+x.cost,s.dailyBudgetMicros)*2;};
    const complete=x=>deltas(projected(x),spent.knownTotalMicros+x.cost).every(d=>d.withinTolerance),toPlan=(x,fallback=false)=>{const n=projected(x),cost=spent.knownTotalMicros+x.cost;return{items:x.items,nutrition:n,totalCostMicros:x.cost,projectedSpendingMicros:cost,withinBudget:cost<=s.dailyBudgetMicros,completeFit:complete(x),minimumTargetFallback:fallback,deltas:deltas(n,cost)};};
    const minimumScore=x=>{const n=projected(x),protein=Math.max(0,(target.protein-n.protein)/Math.max(1,target.protein)),fiber=Math.max(0,(target.fiber-n.fiber)/Math.max(1,target.fiber)),misses=(protein>0?1:0)+(fiber>0?1:0),damage=over(n.calories,target.calories)+['sodium','carbs','fat','sugar','saturated'].reduce((a,k)=>a+over(n[k],target[k]),0)+over(spent.knownTotalMicros+x.cost,s.dailyBudgetMicros)*2;return[misses,protein+fiber,damage,x.cost,x.items.length,signature(x)];};
    const compareTuple=(a,b)=>{for(let i=0;i<a.length;i++){if(a[i]<b[i])return-1;if(a[i]>b[i])return 1;}return 0;};
    const fallback=()=>{const start=projected(fixedState),needsProtein=target.protein>0&&start.protein<target.protein,needsFiber=target.fiber>0&&start.fiber<target.fiber;if(!needsProtein&&!needsFiber)return null;let fallbackBeam=[fixedState];for(const p of products){const expanded=[];for(const b of fallbackBeam)for(let units=0;units<=6&&b.units+units<=20;units++){if(p.plannerItemType==='DRINK'&&b.drinks+units>2)break;expanded.push(units===0?b:add(b,p,units));}fallbackBeam=[...new Map(expanded.map(x=>[signature(x),x])).values()].sort((a,b)=>compareTuple(minimumScore(a),minimumScore(b))).slice(0,200);}const best=fallbackBeam.filter(x=>x.items.length).filter(x=>{const n=projected(x);return(needsProtein&&n.protein>consumed.protein)||(needsFiber&&n.fiber>consumed.fiber);}).sort((a,b)=>compareTuple(minimumScore(a),minimumScore(b)))[0];return best?toPlan(best,true):null;};
    if(!valid(fixedState)){const plan=fallback(),violations=deltas(projected(fixedState),spent.knownTotalMicros+fixedState.cost).filter(d=>!d.withinTolerance&&d.label!=='Protein'&&d.label!=='Fiber'&&d.percentDifference>10);return result(plan?[plan]:[],plan?'A complete plan is impossible because current or fixed values exceed the allowed limits. Showing one best option for unmet minimum goals.':'Planning is blocked by current or fixed-item limits.',violations);}
    let beam=[fixedState];for(const p of products){const expanded=[];for(const b of beam)for(let units=0;units<=6&&b.units+units<=20;units++){if(p.plannerItemType==='DRINK'&&b.drinks+units>2)break;const next=units===0?b:add(b,p,units);if(valid(next))expanded.push(next);}beam=[...new Map(expanded.map(x=>[signature(x),x])).values()].sort((a,b)=>score(a)-score(b)||a.cost-b.cost||signature(a).localeCompare(signature(b))).slice(0,200);}
    const completePlans=beam.filter(x=>x.items.length&&complete(x)).sort((a,b)=>score(a)-score(b)||a.cost-b.cost||signature(a).localeCompare(signature(b))).slice(0,3).map(x=>toPlan(x));if(completePlans.length)return result(completePlans,null);const plan=fallback(),violations=plan?plan.deltas.filter(d=>!d.withinTolerance):[];return result(plan?[plan]:[],plan?'No complete plan fits the current values and limits. Showing one best option for the unmet minimum goals.':'No complete plan fits, and no purchasable combination improves the remaining protein or fiber minimums.',violations);}
  return{KEY,OLD_KEY,number,optional,localDate,empty,migrate,save,seed,totals,report,upsertProduct,findBarcode,addLog,addBulkPurchase,allocateBulkTotal,updateLog,deleteLog,spending,effectiveCalories,plan,defaultSettings,uuid,catalog};
});
