const test=require('node:test');const assert=require('node:assert/strict');const M=require('./model.js');
const Backup=require('./backup.js');
const fs=require('node:fs'),path=require('node:path');
function storage(initial={}){const data={...initial};return{getItem:k=>Object.hasOwn(data,k)?data[k]:null,setItem:(k,v)=>data[k]=String(v),removeItem:k=>delete data[k],data};}
test('migrates legacy values once',()=>{const s=storage({dcr_date:'2026-01-02',dcr_steps:'1234',dcr_burn:'2100',dcr_food:'1800'});const state=M.migrate(s,new Date('2026-01-03T12:00:00'));assert.equal(state.version,4);assert.equal(state.reports['2026-01-02'].steps,1234);assert.equal(M.migrate(s).reports['2026-01-02'].burn,2100);});
test('migrates v2 products and adds the bundled catalog without overwriting',()=>{const old={version:2,selectedDate:'2026-01-03',reports:{},products:{CUSTOM:{barcode:'CUSTOM',name:'Edited Base',calories:1}},logs:[],nextLogId:1};const s=storage({dcr_v2:JSON.stringify(old)}),state=M.migrate(s,new Date('2026-01-03T12:00:00'));assert.equal(state.products.CUSTOM.barcode,null);assert.equal(state.products.CUSTOM.name,'Edited Base');assert.equal(Object.keys(state.products).length,18);assert.equal(state.products['4711089912108'].barcode,'4711089912108');});
test('calculates food totals and standard verdict thresholds',()=>{const state=M.empty('2026-01-03');state.reports['2026-01-03']={burn:2000};const p={barcode:'1',name:'Food',calories:900,protein:30,sodium:100,carbs:0,fat:0,sugar:0,fiber:0,saturated:0};M.addLog(state,'2026-01-03',p,2);const report=M.report(state,'2026-01-03');assert.equal(report.calories,1800);assert.equal(report.verdict,'Maintenance-ish');state.reports['2026-01-03'].burn=2100;assert.equal(M.report(state,'2026-01-03').verdict,'Cut day');});
test('updates and deletes daily log snapshots',()=>{const state=M.empty('2026-01-03');const log=M.addLog(state,'2026-01-03',{barcode:'1',name:'Food',calories:100,protein:1,sodium:2,carbs:0,fat:0,sugar:0,fiber:0,saturated:0},1);M.updateLog(state,log.id,{quantity:3});assert.equal(M.totals(state,'2026-01-03').calories,300);M.deleteLog(state,log.id);assert.equal(M.totals(state,'2026-01-03').entries,0);});
test('supports products without barcodes and rejects duplicate physical barcodes',()=>{const state=M.empty('2026-01-03');M.upsertProduct(state,{productId:'a',barcode:null,name:'Custom'});M.upsertProduct(state,{productId:'b',barcode:'4711089912108',name:'Retail'});assert.equal(M.findBarcode(state,'4711089912108').productId,'b');assert.throws(()=>M.upsertProduct(state,{productId:'c',barcode:'4711089912108',name:'Duplicate'}));});
test('product corrections update linked nutrition but preserve logged costs',()=>{const state=M.empty('2026-01-03'),p=M.upsertProduct(state,{productId:'a',name:'Meal',calories:100,protein:1,purchasePriceMicros:10000000,purchaseUnitServings:1});const log=M.addLog(state,'2026-01-03',p,1,5000000);M.upsertProduct(state,{...p,name:'Corrected',calories:200,purchasePriceMicros:20000000});assert.equal(log.id,state.logs[0].id);assert.equal(state.logs[0].calories,200);assert.equal(state.logs[0].actualPaidTotalMicros,5000000);assert.equal(state.logs[0].catalogCostPerServingMicros,10000000);});
test('spending honors discounts and explicit free items',()=>{const state=M.empty('2026-01-03'),p={productId:'a',name:'Meal',purchasePriceMicros:10000000,purchaseUnitServings:1};M.addLog(state,'2026-01-03',p,2,15000000);M.addLog(state,'2026-01-03',p,1,0);assert.equal(M.spending(state,'2026-01-03').knownTotalMicros,15000000);});
test('planner uses minimum purchase servings and excludes unpriced items',()=>{const state=M.empty('2026-01-03');state.settings={...M.defaultSettings(),calories:1000,protein:50,fiber:5,dailyBudgetMicros:100000000};M.upsertProduct(state,{productId:'priced',name:'Meal',calories:250,protein:15,fiber:2,purchasePriceMicros:20000000,purchaseUnitServings:2});M.upsertProduct(state,{productId:'unknown',name:'Unknown',calories:100});const result=M.plan(state,'2026-01-03');assert.equal(result.excludedUnpricedProducts,1);assert.ok(result.plans.length);assert.ok(result.plans.every(p=>p.items.every(x=>x.servings%2===0)));});
test('planner excludes disabled items, pins fixed items, and limits drinks',()=>{const state=M.empty('2026-01-03');state.settings={...M.defaultSettings(),calories:1000,protein:50,fiber:5,dailyBudgetMicros:100000000};M.upsertProduct(state,{productId:'disabled',name:'Disabled',calories:900,purchasePriceMicros:1,includeInPlanner:false});M.upsertProduct(state,{productId:'fixed',name:'Fixed',calories:200,protein:10,purchasePriceMicros:10000000,alwaysIncludeInPlanner:true});for(let i=0;i<4;i++)M.upsertProduct(state,{productId:`drink${i}`,name:`Drink ${i}`,calories:100,protein:5,purchasePriceMicros:5000000,plannerItemType:'DRINK'});const result=M.plan(state,'2026-01-03');assert.equal(result.excludedFromPlanningProducts,1);assert.ok(result.plans.length);assert.ok(result.plans.every(p=>p.items.some(x=>x.productId==='fixed'&&x.fixed)));assert.ok(result.plans.every(p=>p.items.filter(x=>x.itemType==='DRINK').reduce((n,x)=>n+x.purchaseUnits,0)<=2));});
test('ignored log price is retained but excluded from spending',()=>{const state=M.empty('2026-01-03'),p={productId:'a',name:'Meal',purchasePriceMicros:10000000,purchaseUnitServings:1};const log=M.addLog(state,'2026-01-03',p,2,15000000,true);assert.equal(log.actualPaidTotalMicros,15000000);assert.equal(M.spending(state,'2026-01-03').knownTotalMicros,0);});
test('encrypted browser backup authenticates password and payload',async()=>{const payload={schemaVersion:1,products:[{productId:'a'}]},password='correct horse';const encrypted=await Backup.encrypt(payload,password);assert.deepEqual(await Backup.decrypt(encrypted,password),payload);await assert.rejects(()=>Backup.decrypt(encrypted,'wrong password'));encrypted[encrypted.length-1]^=1;await assert.rejects(()=>Backup.decrypt(encrypted,password));});
test('Android and browser catalogs contain the same 17 stable IDs',()=>{const android=JSON.parse(fs.readFileSync(path.join(__dirname,'../app/src/main/assets/preloaded_products.json'),'utf8'));assert.equal(android.products.length,17);assert.equal(new Set(android.products.map(x=>x.id)).size,17);assert.deepEqual(new Set(android.products.map(x=>x.id)),new Set(M.catalog.map(x=>x.productId)));});
